### ISSUE TITLE
Vertically centre nav & grid column issues

### ISSUE THREAD

**Issue by ZeeCote** [ZeeCote/modularity-mindfulness#1]
Hello, I'm not sure how to vertically centre my navigation in this assignment. 
I also don't understand why my grid-template-columns is not working in my articles, they don't seem to was to go next to each other. 

@hellachella
@JessJodoin

**Comment by JessJodoin** [comment]
For the nav, I would remove the image from the header so that I could make the header a flex container:
```
header {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 1rem .5rem;
}
```
And in the media query add this for the header:
```
header {
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
  }
```

For the grid issue, you missed an 's' on the `.sections` (line 152) so it doesn't match the class you gave put in your index
